import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Title For Child",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
